const DHmiercoles = {
    estasEn: "Hoja de Miercoles",
    paginas: [
        {
            path: "/sitraina/reglamentos",
            seccion: "Reglamentos"
        },
        {
            path: "/sitraina/juntadirectiva",
            seccion: "Junta Directiva"
        },
        {
            path: "/sitraina/fiscalia",
            seccion: "Fiscalia"
        },
        // {
        //     path: "",
        //     seccion: "Seccionales"
        // },
        {
            path: "/sitraina/convenios",
            seccion: "Convenios"
        },
        // {
        //     path: "/sitraina/contactenos",
        //     seccion: "Contactenos"
        // }
    ],
    multimedia: [
        {
            path: "/sitraina/AlbumnesFotos",
            seccion: "Albumnes/Fotos"
        },
        {
            path: "/sitraina/AudiosVideos",
            seccion: "Audios/Videos"
        }
    ],
    HMiercoles: [
        {
            titulo: "Hoja de Miercoles",
            lema: "Las Hojas de Miercoles estan acomodadas por listas dentro de las opciones desplegables teniendo de titular su año correspondiente que se muestran a continuacion."
        }
    ],
    HM2022: [
      // Hoja de Miercoles proxima
      // {
      //     año: 2022,
      //     titulo: "Hoja de Miercoles 23 de Marzo, 2022",
      //     mes: "Marzo",
      //     fecha: 23,
      //     link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2022/Hoja_de_Miercoles-23_marzo_2022.pdf",
      // },
      // Hoja de Miercoles Actual
      // Hoja_de_Miercoles-21_marzo_2022-Edicion_Especial
      {
        año: 2022,
        titulo: "Hoja de Lunes 21 de Marzo, 2022 - Edicion Especial",
        mes: "Marzo",
        fecha: 21,
        link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2022/Hoja_de_Miercoles-21_marzo_2022-Edicion_Especial.pdf",
      },
      {
        año: 2022,
        titulo: "Hoja de Miercoles 16 de Marzo, 2022",
        mes: "Marzo",
        fecha: 16,
        link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2022/Hoja_de_Miercoles-16_marzo_2022.pdf",
      },
      {
          año: 2022,
          titulo: "Hoja de Miercoles 09 de Marzo, 2022",
          mes: "Marzo",
          fecha: 9,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2022/Hoja_de_Miercoles-09_marzo_2022.pdf",
      },
      {
          año: 2022,
          titulo: "Hoja de Miercoles 02 de Marzo, 2022",
          mes: "Marzo",
          fecha: 2,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2022/Hoja_de_Miercoles-02_marzo_2022.pdf",
      },
      {
        año: 2022,
        titulo: "Hoja de Lunes 28 de Febrero, 2022 - Edicion Especial",
        mes: "Febrero",
        fecha: 28,
        link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2022/Hoja_de_Miercoles-28_febrero_2022-Edicion_Especial.pdf",
      },
      {
        año: 2022,
        titulo: "Hoja de Miercoles 23 de Febrero, 2022",
        mes: "Febrero",
        fecha: 23,
        link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2022/Hoja_de_Miercoles-23_febrero_2022.pdf",
      },
      {
        año: 2022,
        titulo: "Hoja de Miercoles 16 de Febrero, 2022",
        mes: "Febrero",
        fecha: 16,
        link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2022/Hoja_de_Miercoles-16_febrero_2022.pdf",
      },
      {
        año: 2022,
        titulo: "Hoja de Miercoles 09 de Febrero, 2022",
        mes: "Febrero",
        fecha: 9,
        link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2022/Hoja_de_Miercoles-09_febrero_2022.pdf",
      },
      {
        año: 2022,
        titulo: "Hoja de Miercoles 02 de Febrero, 2022",
        mes: "Febrero",
        fecha: 2,
        link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2022/Hoja_de_Miercoles-02_febrero_2022.pdf",
      },
      {
        año: 2022,
        titulo: "Hoja de Miercoles 26 de Enero, 2022",
        mes: "Enero",
        fecha: 26,
        link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2022/Hoja_de_Miercoles-26_enero_2022.pdf",
      },
      {
        año: 2022,
        titulo: "Hoja de Miercoles 19 de Enero, 2022",
        mes: "Enero",
        fecha: 19,
        link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2022/Hoja_de_Miercoles-19_enero_2022.pdf",
      },
      {
        año: 2022,
        titulo: "Hoja de Miercoles 12 de Enero, 2022",
        mes: "Enero",
        fecha: 12,
        link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2022/Hoja_de_Miercoles-12_enero_2022.pdf",
      },
    ],
    HM2021: [
        {
          año: 2021,
          titulo: "Hoja de Miercoles 22 de Diciembre, 2021",
          mes: "Diciembre",
          fecha: 22,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-22_diciembre_2021.pdf",
        },
        // Hoja de Miercoles Actual
        {
          año: 2021,
          titulo: "Hoja de Miercoles 15 de Diciembre, 2021",
          mes: "Diciembre",
          fecha: 15,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-15_diciembre_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 22 de Diciembre, 2021",
          mes: "Diciembre",
          fecha: 22,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-22_diciembre_2021.pdf",
        },
        // Hoja de Miercoles Actual
        {
          año: 2021,
          titulo: "Hoja de Miercoles 08 de Diciembre, 2021",
          mes: "Diciembre",
          fecha: 8,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-08_diciembre_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 01 de Diciembre, 2021",
          mes: "Diciembre",
          fecha: 1,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-01_diciembre_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 24 de Noviembre, 2021",
          mes: "Noviembre",
          fecha: 24,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-24_noviembre_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 17 de Noviembre, 2021",
          mes: "Noviembre",
          fecha: 17,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-17_noviembre_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 10 de Noviembre, 2021",
          mes: "Noviembre",
          fecha: 10,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-10_noviembre_2021.pdf",
        },{
          año: 2021,
          titulo: "Hoja de Miercoles 05 de Noviembre, 2021 - Edicion Especial",
          mes: "Noviembre",
          fecha: 5,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-05_noviembre_2021-Edicion_Especial.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 03 de Noviembre, 2021",
          mes: "Noviembre",
          fecha: 3,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-03_noviembre_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 27 de Octubre, 2021",
          mes: "Octubre",
          fecha: 27,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-27_octubre_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 20 de Octubre, 2021",
          mes: "Octubre",
          fecha: 20,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-20_octubre_2021.pdf",
        },{
          año: 2021,
          titulo: "Hoja de Miercoles 13 de Octubre, 2021",
          mes: "Octubre",
          fecha: 13,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-13_octubre_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 06 de Octubre, 2021",
          mes: "Octubre",
          fecha: 6,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-06_octubre_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 14 de Julio, 2021",
          mes: "Julio",
          fecha: 14,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-14_julio_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 07 de Julio, 2021",
          mes: "Julio",
          fecha: 7,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-07_julio_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 30 de Junio, 2021",
          mes: "Junio",
          fecha: 30,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-30_junio_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 23 de Junio, 2021",
          mes: "Junio",
          fecha: 23,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-23_junio_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 18 de Junio, 2021 - Edicion Especial",
          mes: "Junio",
          fecha: 18,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-18_junio_2021-Edicion_Especial.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 09 de Junio, 2021",
          mes: "Junio",
          fecha: 9,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-09_junio_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 26 de Mayo, 2021 - Edicion Especial",
          mes: "Junio",
          fecha: 26,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-26_mayo_2021-Edicion_Especial.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 26 de Mayo, 2021",
          mes: "Mayo",
          fecha: 26,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-26_mayo_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 19 de Mayo, 2021",
          mes: "Mayo",
          fecha: 19,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-19_mayo_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 12 de Mayo, 2021 - Edicion Especial",
          mes: "Mayo",
          fecha: 12,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-12_mayo_2021-Edicion_Especial.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 12 de Mayo, 2021",
          mes: "Mayo",
          fecha: 12,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-12_mayo_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 21 de Abril, 2021",
          mes: "Abril",
          fecha: 21,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-21_abril_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 09 de Abril, 2021 - Edicion Especial",
          mes: "Abril",
          fecha: 9,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-09_abril_2021-Edicion_Especial.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 07 de Abril, 2021",
          mes: "Abril",
          fecha: 7,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-07_abril_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 24 de Marzo, 2021",
          mes: "Marzo",
          fecha: 24,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-24_marzo_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 17 de Marzo, 2021 - Edicion Especial",
          mes: "Marzo",
          fecha: 17,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-17_marzo_2021-Edicion_Especial.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 17 de Marzo, 2021",
          mes: "Marzo",
          fecha: 17,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-17_marzo_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 10 de Marzo, 2021",
          mes: "Marzo",
          fecha: 10,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-10_marzo_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 03 de Marzo, 2021",
          mes: "Marzo",
          fecha: 3,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-03_marzo_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 24 de Febrero, 2021",
          mes: "Febrero",
          fecha: 24,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-24_febrero_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 17 de Febrero, 2021",
          mes: "Febrero",
          fecha: 17,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-17_febrero_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 10 de Febrero, 2021",
          mes: "Febrero",
          fecha: 10,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-10_febrero_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 03 de Febrero, 2021",
          mes: "Febrero",
          fecha: 3,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-03_febrero_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 27 de Enero, 2021",
          mes: "Enero",
          fecha: 27,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-27_enero_2021.pdf",
        },
        {
          año: 2021,
          titulo: "Hoja de Miercoles 20 de Enero, 2021",
          mes: "Enero",
          fecha: 20,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2021/Hoja_de_Miercoles-20_enero_2021.pdf",
        },
      ],
      HM2020: [
        {
          año: 2020,
          titulo: "Hoja de Miercoles 16 de Diciembre, 2020",
          mes: "Diciembre",
          fecha: 16,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2020/Hoja_de_Miercoles-16_diciembre_2020.pdf",
        },
        {
          año: 2020,
          titulo: "Hoja de Miercoles 09 de Diciembre, 2020",
          mes: "Diciembre",
          fecha: 9,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2020/Hoja_de_Miercoles-09_diciembre_2020.pdf",
        },
        {
          año: 2020,
          titulo: "Hoja de Miercoles 04 de Diciembre, 2020 - Edicion Especial",
          mes: "Diciembre",
          fecha: 4,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2020/Hoja_de_Miercoles-04_diciembre_2020-Edicion_Especial.pdf",
        },
        {
          año: 2020,
          titulo: "Hoja de Miercoles 02 de Diciembre, 2020 - Edicion Especial",
          mes: "Diciembre",
          fecha: 2,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2020/Hoja_de_Miercoles-02_diciembre_2020-Edicion_Especial.pdf",
        },
        {
          año: 2020,
          titulo: "Hoja de Miercoles 25 de Noviembre, 2020",
          mes: "Noviembre",
          fecha: 25,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2020/Hoja_de_Miercoles-25_noviembre_2020.pdf",
        },
        {
          año: 2020,
          titulo: "Hoja de Miercoles 18 de Noviembre, 2020",
          mes: "Noviembre",
          fecha: 18,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2020/Hoja_de_Miercoles-18_noviembre_2020.pdf",
        },
        {
          año: 2020,
          titulo: "Hoja de Miercoles 04 de Noviembre, 2020",
          mes: "Noviembre",
          fecha: 4,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2020/Hoja_de_Miercoles-04_noviembre_2020.pdf",
        },
        {
          año: 2020,
          titulo: "Hoja de Miercoles 28 de Octubre, 2020",
          mes: "Octubre",
          fecha: 28,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2020/Hoja_de_Miercoles-28_octubre_2020.pdf",
        },
        {
          año: 2020,
          titulo: "Hoja de Miercoles 21 de Octubre, 2020",
          mes: "Octubre",
          fecha: 21,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2020/Hoja_de_Miercoles-21_octubre_2020.pdf",
        },
        {
          año: 2020,
          titulo: "Hoja de Miercoles 14 de Octubre, 2020",
          mes: "Octubre",
          fecha: 14,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2020/Hoja_de_Miercoles-14_octubre_2020.pdf",
        },
        {
          año: 2020,
          titulo: "Hoja de Miercoles 07 de Octubre, 2020",
          mes: "Octubre",
          fecha: 7,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2020/Hoja_de_Miercoles-07_octubre_2020.pdf",
        },
        {
          año: 2020,
          titulo: "Hoja de Miercoles 30 de Septiembre, 2020",
          mes: "Septiembre",
          fecha: 30,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2020/Hoja_de_Miercoles-30_septiembre_2020.pdf",
        },
        {
          año: 2020,
          titulo: "Hoja de Miercoles 17 de Septiembre, 2020 - Edicion Especial",
          mes: "Septiembre",
          fecha: 17,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2020/Hoja_de_Miercoles-17_septiembre_2020-Edicion_Especial.pdf",
        },
        {
          año: 2020,
          titulo: "Hoja de Miercoles 09 de Septiembre, 2020",
          mes: "Septiembre",
          fecha: 9,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2020/Hoja_de_Miercoles-09_septiembre_2020.pdf",
        },
        {
          año: 2020,
          titulo: "Hoja de Miercoles 02 de Septiembre, 2020",
          mes: "Septiembre",
          fecha: 2,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2020/Hoja_de_Miercoles-02_septiembre_2020.pdf",
        },
        {
          año: 2020,
          titulo: "Hoja de Miercoles 26 de Agosto, 2020",
          mes: "Agosto",
          fecha: 26,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2020/Hoja_de_Miercoles-26_agosto_2020.pdf",
        },
        {
          año: 2020,
          titulo: "Hoja de Miercoles 12 de Agosto, 2020",
          mes: "Agosto",
          fecha: 12,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2020/Hoja_de_Miercoles-12_agosto_2020.pdf",
        },
        {
          año: 2020,
          titulo: "Hoja de Miercoles 05 de Agosto, 2020",
          mes: "Agosto",
          fecha: 5,
          link: "../../Documentos/hoja de miercoles/Hoja de Miercoles 2020/Hoja_de_Miercoles-05_agosto_2020.pdf",
        },
      ],
}

export default DHmiercoles