const InfoDataTable = {
  HM2020: [
    {
      año: 2021,
      titulo: "Sindicalismo",
      mes: "Mayo",
      fecha: 5,
      informacion: "Ver",
    },
    {
      año: 2021,
      titulo: "Regulaciones",
      mes: "Abril",
      fecha: 28,
      informacion: "Ver",
    },
    {
      año: 2021,
      titulo: "Regulaciones",
      mes: "Abril",
      fecha: 21,
      informacion: "Ver",
    },
    {
      año: 2021,
      titulo: "Regulaciones",
      mes: "Abril",
      fecha: 14,
      informacion: "Ver",
    },
    {
      año: 2021,
      titulo: "Regulaciones",
      mes: "Abril",
      fecha: 7,
      informacion: "Ver",
    },
    {
      año: 2021,
      titulo: "Administracion sin regulacion",
      mes: "Marzo",
      fecha: 31,
      informacion: "Ver",
    },
    {
      año: 2021,
      titulo: "Administracion sin regulacion",
      mes: "Marzo",
      fecha: 24,
      informacion: "Ver",
    },
    {
      año: 2021,
      titulo: "Administracion sin regulacion",
      mes: "Marzo",
      fecha: 17,
      informacion: "Ver",
    },
    {
      año: 2021,
      titulo: "Administracion sin regulacion",
      mes: "Marzo",
      fecha: 10,
      informacion: "Ver",
    },
    {
      año: 2021,
      titulo: "Administracion sin regulacion",
      mes: "Marzo",
      fecha: 3,
      informacion: "Ver",
    },
    {
      año: 2021,
      titulo: "Trabajadores",
      mes: "Febrero",
      fecha: 24,
      informacion: "Ver",
    },
    {
      año: 2021,
      titulo: "Trabajadores",
      mes: "Febrero",
      fecha: 17,
      informacion: "Ver",
    },
    {
      año: 2021,
      titulo: "Trabajadores",
      mes: "Febrero",
      fecha: 10,
      informacion: "Ver",
    },
    {
      año: 2021,
      titulo: "Trabajadores",
      mes: "Febrero",
      fecha: 3,
      informacion: "Ver",
    },
    {
      año: 2021,
      titulo: "Sindicato",
      mes: "Enero",
      fecha: 27,
      informacion: "Ver",
    },
    {
      año: 2021,
      titulo: "Sindicato",
      mes: "Enero",
      fecha: 20,
      informacion: "Ver",
    },
    {
      año: 2021,
      titulo: "Sindicato",
      mes: "Enero",
      fecha: 13,
      informacion: "Ver",
    },
    {
      año: 2021,
      titulo: "Sindicato",
      mes: "Enero",
      fecha: 6,
      informacion: "Ver",
    },
  ],
  HM2020: [
    {
      año: 2020,
      titulo: "Sindicalismo",
      mes: "Mayo",
      fecha: 5,
      informacion: "Ver",
    },
    {
      año: 2020,
      titulo: "Regulaciones",
      mes: "Abril",
      fecha: 28,
      informacion: "Ver",
    },
    {
      año: 2020,
      titulo: "Regulaciones",
      mes: "Abril",
      fecha: 21,
      informacion: "Ver",
    },
    {
      año: 2020,
      titulo: "Regulaciones",
      mes: "Abril",
      fecha: 14,
      informacion: "Ver",
    },
    {
      año: 2020,
      titulo: "Regulaciones",
      mes: "Abril",
      fecha: 7,
      informacion: "Ver",
    },
    {
      año: 2020,
      titulo: "Administracion sin regulacion",
      mes: "Marzo",
      fecha: 31,
      informacion: "Ver",
    },
    {
      año: 2020,
      titulo: "Administracion sin regulacion",
      mes: "Marzo",
      fecha: 24,
      informacion: "Ver",
    },
    {
      año: 2020,
      titulo: "Administracion sin regulacion",
      mes: "Marzo",
      fecha: 17,
      informacion: "Ver",
    },
    {
      año: 2020,
      titulo: "Administracion sin regulacion",
      mes: "Marzo",
      fecha: 10,
      informacion: "Ver",
    },
    {
      año: 2020,
      titulo: "Administracion sin regulacion",
      mes: "Marzo",
      fecha: 3,
      informacion: "Ver",
    },
    {
      año: 2020,
      titulo: "Trabajadores",
      mes: "Febrero",
      fecha: 24,
      informacion: "Ver",
    },
    {
      año: 2020,
      titulo: "Trabajadores",
      mes: "Febrero",
      fecha: 17,
      informacion: "Ver",
    },
    {
      año: 2020,
      titulo: "Trabajadores",
      mes: "Febrero",
      fecha: 10,
      informacion: "Ver",
    },
    {
      año: 2020,
      titulo: "Trabajadores",
      mes: "Febrero",
      fecha: 3,
      informacion: "Ver",
    },
    {
      año: 2020,
      titulo: "Sindicato",
      mes: "Enero",
      fecha: 27,
      informacion: "Ver",
    },
    {
      año: 2020,
      titulo: "Sindicato",
      mes: "Enero",
      fecha: 20,
      informacion: "Ver",
    },
    {
      año: 2020,
      titulo: "Sindicato",
      mes: "Enero",
      fecha: 13,
      informacion: "Ver",
    },
    {
      año: 2020,
      titulo: "Sindicato",
      mes: "Enero",
      fecha: 6,
      informacion: "Ver",
    },
  ],
};

export default InfoDataTable;
